apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: iam.miloapis.com-protectedresource
spec:
  serviceRef:
    name: "iam.miloapis.com"
  kind: ProtectedResource
  plural: protectedresources
  singular: protectedresource
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
