version: "3.9"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    command: >
      etcd --advertise-client-urls http://0.0.0.0:2379
           --listen-client-urls    http://0.0.0.0:2379
           --data-dir /etcd-data
    ports:
      - "2379:2379"

  milo-controller:
    image: milo-apiserver:dev
    command: >
      controller-manager
        --control-plane-scope=core
        --kubeconfig=/etc/milo/root-kubeconfig.yaml
        --system-namespace=milo-system
        --leader-elect-resource-namespace=milo-system
        --authorization-always-allow-paths=/debug/controllers/garbage-collector-controller/graph,/debug/controllers/garbage-collector-controller/graph/
        --authentication-skip-lookup
        --cert-dir=/certs
        --tls-cert-file=/certs/tls.crt
        --tls-private-key-file=/certs/tls.key
        --v=6
    environment:
      - TZ=UTC
    volumes:
      - ./certs:/certs:ro
      - ./root-kubeconfig.yaml:/etc/milo/root-kubeconfig.yaml:ro
    depends_on:
      - milo
    ports:
      - "10252:10252"
      - "10257:10257"

  milo:
    image: milo-apiserver:dev
    environment:
      - TZ=UTC
    command: >
      apiserver
        --etcd-servers=http://etcd:2379
        --secure-port=8443
        --bind-address=0.0.0.0
        --system-namespace=milo-system
        --service-account-issuer=https://milo.localtest.me
        --service-account-signing-key-file=/certs/sa.key
        --service-account-key-file=/certs/sa.key
        --authorization-mode=AlwaysAllow
        --token-auth-file=/certs/static-token.csv 
        --v=4
    ports:
      - "8443:8443"
    volumes:
      - ./certs:/certs:ro 
      - etcd-data:/etcd-data

    depends_on:
      - etcd

volumes:
  etcd-data: