apiVersion: v1
kind: Config

clusters:
# ── 1. root Milo control-plane ───────────────────────────
- name: milo-local
  cluster:
    server: https://milo:8443          # docker-compose port
    insecure-skip-tls-verify: true

# ── 2. project “alpha” virtual-cluster ──────────────────
- name: milo-project-alpha
  cluster:
    server: https://milo:8443/projects/alpha/control-plane
    insecure-skip-tls-verify: true

# ── 3. project “beta” virtual-cluster ───────────────────
- name: milo-project-beta
  cluster:
    server: https://milo:8443/projects/beta/control-plane
    insecure-skip-tls-verify: true

# ── 4. project “gamma” virtual-cluster ──────────────────
- name: milo-project-gamma
  cluster:
    server: https://milo:8443/projects/gamma/control-plane
    insecure-skip-tls-verify: true

users:
- name: milo-dev
  user:
    token: devtoken                         # first column of static-token.csv

contexts:
# default root context
- name: milo
  context:
    cluster: milo-local
    user: milo-dev

# project-scoped contexts
- name: alpha
  context:
    cluster: milo-project-alpha
    user: milo-dev

- name: beta
  context:
    cluster: milo-project-beta
    user: milo-dev

- name: gamma
  context:
    cluster: milo-project-gamma
    user: milo-dev

current-context: milo