# This IAM policy allows all authenticated users to manage their own user account
name: iam.datumapis.com/services/iam.datumapis.com/roles/newUser
spec:
  bindings:
  - role: services/iam.datumapis.com/roles/newUser
    members:
    - allAuthenticatedUsers