# This IAM policy allows all authenticated users to use the policyAdmin role
name: iam.datumapis.com/services/iam.datumapis.com/roles/policyAdmin
spec:
  bindings:
  # Allow the service-infrastructure service account to manage services
  # registered with the IAM service.
  - role: services/iam.datumapis.com/roles/roleUser
    members:
    - allAuthenticatedUsers
