apiVersion: v1
kind: Service
metadata:
  name: milo-apiserver
  labels:
    app: milo-apiserver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: milo-apiserver
  ports:
  - name: https
    port: 6443
    protocol: TCP
    targetPort: https
