apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: resourcemanager.miloapis.com-organization
spec:
  serviceRef:
    name: "resourcemanager.miloapis.com"
  kind: Organization
  plural: organizations
  singular: organization
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
    - use
