apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:controller:milo-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: milo-controller-manager
subjects:
  - kind: ServiceAccount
    name: milo-controller-manager
    namespace: milo-system
