---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milo-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.miloapis.com
  resources:
  - groupmemberships
  verbs:
  - delete
  - list
- apiGroups:
  - iam.miloapis.com
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.miloapis.com
  resources:
  - groups/finalizers
  - users/status
  verbs:
  - update
- apiGroups:
  - iam.miloapis.com
  resources:
  - groups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.miloapis.com
  resources:
  - policybindings
  verbs:
  - delete
  - list
  - update
- apiGroups:
  - iam.miloapis.com
  resources:
  - userdeactivations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iam.miloapis.com
  resources:
  - users
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - organizationmemberships
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - organizationmemberships/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - organizations
  verbs:
  - get
  - list
  - watch
