apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: apiextensions-reader
spec:
  launchStage: Beta
  includedPermissions:
    # Read-only permissions for API Extensions resources
    - apiextensions.k8s.io/customresourcedefinitions.get
    - apiextensions.k8s.io/customresourcedefinitions.list
    - apiextensions.k8s.io/customresourcedefinitions.watch
