roleId: roleAdmin
parent: services/iam.datumapis.com
name: services/iam.datumapis.com/roles/roleAdmin
displayName: IAM Role Admin
spec:
  launchStage: Stable
  includedPermissions:
  - iam.datumapis.com/roles.create
  - iam.datumapis.com/roles.list
  - iam.datumapis.com/roles.get
  - iam.datumapis.com/roles.update
  - iam.datumapis.com/roles.delete
