roleId: serviceAccountAdmin
parent: services/iam.datumapis.com
name: services/iam.datumapis.com/roles/serviceAccountAdmin
displayName: IAM Service Account Admin
spec:
  launchStage: Stable
  includedPermissions:
  - iam.datumapis.com/serviceAccounts.get
  - iam.datumapis.com/serviceAccounts.list
  - iam.datumapis.com/serviceAccounts.create
  - iam.datumapis.com/serviceAccounts.update
  - iam.datumapis.com/serviceAccounts.delete
  - iam.datumapis.com/serviceAccountKeys.get
  - iam.datumapis.com/serviceAccountKeys.list
  - iam.datumapis.com/serviceAccountKeys.create
  - iam.datumapis.com/serviceAccountKeys.update
  - iam.datumapis.com/serviceAccountKeys.delete
