apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: owner
spec:
  launchStage: Beta
  inheritedRoles:
    - name: project-manager
      namespace: milo-system

  # TODO: Remove this being a required field.
  includedPermissions:
    - resourcemanager.miloapis.com/projects.get
