apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: core-configmap
spec:
  serviceRef:
    name: "core.miloapis.com"
  kind: ConfigMap
  plural: configmaps
  singular: configmap
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
