apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: core-configmap
spec:
  serviceRef:
    name: "core"
  kind: ConfigMap
  plural: configmaps
  singular: configmap
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
