apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: core-event
spec:
  serviceRef:
    name: "core.miloapis.com"
  kind: Event
  plural: events
  singular: event
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
