apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: core-namespace
spec:
  serviceRef:
    name: "core.miloapis.com"
  kind: Namespace
  plural: namespaces
  singular: namespace
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
