apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: core-secret
spec:
  serviceRef:
    name: "core"
  kind: Secret
  plural: secrets
  singular: secret
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
