version: '3'

tasks:
  default:
    cmds:
      - task --list-all

  api-linter-install:
    desc: Install/update api-linter.
    run: once
    cmds:
      - go install github.com/googleapis/api-linter/cmd/api-linter@v1.67.3

  format:
    desc: Format the protobuf definitions.
    cmds:
      - buf format --write

  buf-build:
    desc: Build the buf image and download the external dependencies
    run: once
    cmds:
      - buf build

  ## $(grep "commit" ../buf.lock | awk '{print $2}') gets the commit hash from
  ## buf.lock or importing external dependencies
  lint:
    desc: Run the AIP linter against protobuf definitions.
    deps:
      - api-linter-install
      - buf-build
    cmds:
      - api-linter -I /home/vscode/.cache/buf/v3/modules/b5/buf.build/googleapis/googleapis/$(grep "commit" ../buf.lock | awk '{print $2}')/files
        --config api-linter.yaml
        --set-exit-status
        ./datum/**/*.proto
        ./datum/**/**/*.proto



