name: "IAM API testing"
on:
  push:
    paths:
      - '**/*.go'

jobs:
  iam_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: go mod download
      - name: Run IAM tests
        run: go test -timeout 5m ./...
